name: Publish Release Info
description: Publish a release notification to Slack with a changelog and list to related tools

author: David Dias <thedaviddias@gmail.com>

branding:
  icon: 'message-circle'
  color: 'gray-dark'

inputs:
  github_token:
    description: Your GitHub token for authentication. It is used to get the repository information and generate the changelog.
    required: true

  tag_regex:
    description: 'A regular expression to match against git tags. The first capture group should be the version number.'
    required: false
    default: '^v[0-9]+\.[0-9]+\.[0-9]+$'  # Matches the semver notation (v1.0.0") by default

  contributor_replace_regex:
    description: An optional regular expression (regex) pattern to identify characters in the `contributor` name that will be replaced.
    required: false

  contributor_replace_char:
    description: The character that will replace specific characters in the `contributor` name.
    required: false

  repo:
    description: The repository for which the action should generate the changelog and post a release notification. If not provided, it defaults to the repository where the action is running.
    required: false

  jira_ticket_prefix:
    description: The specific letter or pattern to target in the commit title.
    required: false

  jira_instance_url:
    description: The custom URL of the JIRA instance.
    required: false

  slack_webhook_urls:
    description: Comma-separated list of Slack Webhook URLs to which the action will send a message with the changelog and release details.
    required: false

  sentry_project_name:
    description: The name of the Sentry project related to the repository. This will be included in the Slack notification for quick access to the project error tracking.
    required: false

  sentry_project_id:
    description: The id of the Sentry project. This is used to fetch the related issues and include them in the Slack notification.
    required: false

  grafana_dashboard_link:
    description: The URL link to the Grafana dashboard related to the repository. This link will be included in the Slack notification for easy access to relevant analytics.
    required: false

  time_zone_offset:
    description: 'Timezone offset in minutes from UTC. Positive for timezones ahead of UTC, negative for those behind.'
    required: false
    default: '0'  # Default is 0, i.e., UTC time

runs:
  using: node16
  main: dist/index.js
